version: "3"
services:
  manager:
    container_name: manager
    build:
      context: .
      dockerfile: Dockerfile.manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./server_app:/server_app
      - ./manager_logs:/server_app/manager_logs
      - ./logs:/logs

    environment:
      MANAGER_SLEEP_TIME: 30
      API_SERVER: https://se.inf.tu-dresden.de/debs2019/
      API_RESULT_PATH: /result
      API_SCHEDULE_PATH: /schedule
